trigger:
    - main

jobs:
    - job: Compliance
      pool:
          vmImage: 'windows-latest'
      steps:
          - task: PoliCheck@1
            displayName: '🌎 PoliCheck'
            inputs:
                inputType: 'Basic'
                targetType: 'F'
                targetArgument: '$(Build.SourcesDirectory)'
                result: 'PoliCheck.xml'
                optionsXS: 1 # Scan subfolders
                optionsPE: 1 # Enable exclusions
                # Exclude folders like node_modules, dist, .git etc.
                optionsUEPATH: '$(Build.SourcesDirectory)/policheck/UserExclusion.xml'

      # Guardian and ESLint are built on dotnet and need a Windows VM to run
    - job: Security
      pool:
          vmImage: 'windows-latest'
      # Run the 1ES ESLint task using Guardian
      steps:
          - task: ESLint@1
            displayName: '🛡 Guardian: ESLint'
            inputs:
                Configuration: 'recommended'
                TargetType: 'eslint'
                TargetsESLint: |
                    $(Build.SourcesDirectory)/**/*.js
                ErrorLevel: 'warn'
