pr:
  branches:
    include:
      - main
variables:
  Codeql.Enabled: true
resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    customBuildTags:
      - ES365AIMigrationTooling-BulkMigrated
    stages:
      - stage: security_compliance
        displayName: "Security & Compliance"
        jobs:
          - job: compliance
            templateContext:
              outputs:
                - output: pipelineArtifact
                  displayName: "Create log artifact"
                  targetPath: '..\_sdt\logs\PoliCheck\PoliCheck.xml'
                  artifactName: "PoliCheck"
            steps:
              - task: PoliCheck@1
                displayName: "Run PoliCheck"
                inputs:
                  inputType: "Basic"
                  targetType: "F"
                  targetArgument: "$(Build.SourcesDirectory)"
                  result: "PoliCheck.xml"
                  optionsXS: 1
                  optionsPE: 1
                  optionsUEPATH: "$(Build.SourcesDirectory)/policheck/UserExclusion.xml"
          - job: security
            steps:
              - task: ESLint@1
                displayName: "Guardian: ESLint"
                inputs:
                  Configuration: "recommended"
                  TargetType: "eslint"
                  TargetsESLint: |
                    $(Build.SourcesDirectory)/**/*.ts
                  ErrorLevel: "warn"
      - stage: build_lint
        displayName: "Build & Lint"
        jobs:
          - job: lint
            timeoutInMinutes: 10
            steps:
              - task: NodeTool@0
                displayName: "Setup Node"
                inputs:
                  versionSpec: "18.x"
              - script: npm install
                displayName: "Install Dependencies"
              - script: npm run lint
                displayName: "Run Lint Check"
              - script: npm run fmt
                displayName: "Run Format Check"
          - job: build
            timeoutInMinutes: 10
            templateContext:
              outputs:
                - output: pipelineArtifact
                  displayName: "Publish Artifacts"
                  targetPath: "$(System.DefaultWorkingDirectory)/dist"
                  artifactName: "drop"
            steps:
              - task: NodeTool@0
                displayName: "Setup Node"
                inputs:
                  versionSpec: "18.x"
              - script: npm install
                displayName: "Install Dependencies"
              - script: npm run build
                displayName: "Build Toolkit"
              - task: CopyFiles@2
                displayName: "Copy to Staging"
                inputs:
                  SourceFolder: "$(System.DefaultWorkingDirectory)/dist"
                  Contents: |
                    **/*
                  TargetFolder: "$(Build.ArtifactStagingDirectory)"
