trigger:
    - main

jobs:
    - job: Compliance
      pool:
          vmImage: 'windows-latest'
      steps:
          - task: PoliCheck@1
            displayName: '🌎 PoliCheck'
            inputs:
                inputType: 'Basic'
                targetType: 'F'
                targetArgument: '$(Build.SourcesDirectory)'
                result: 'PoliCheck.xml'
                optionsXS: 1 # Scan subfolders
                optionsPE: 1 # Enable exclusions
                optionsUEPATH: '$(Build.SourcesDirectory)/policheck/UserExclusion.xml'

          - task: PublishBuildArtifacts@1
            displayName: 'Create log artifact'
            inputs:
                pathToPublish: '..\_sdt\logs\PoliCheck\PoliCheck.xml'
                artifactName: 'PoliCheck'

    - job: Security
      pool:
          vmImage: 'windows-latest'
      steps:
          - task: ESLint@1
            displayName: '🛡 Guardian: ESLint'
            inputs:
                Configuration: 'recommended'
                TargetType: 'eslint'
                TargetsESLint: |
                    $(Build.SourcesDirectory)/**/*.js
                ErrorLevel: 'warn'
