name: toolkit-ci

on: pull_request

jobs:
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2

            - name: Setup Node 💾
              uses: actions/setup-node@v2
              with:
                  node-version: '18'

            - name: Install Dependencies 📥
              run: npm install

            - name: Run Lint Check 🔍
              run: npm run lint

            - name: Run Format Check 🌸
              run: npm run fmt

    build-toolkit:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2

            - name: Setup Node 💾
              uses: actions/setup-node@v2
              with:
                  node-version: '18'

            - name: Install Dependencies 📥
              run: npm install

            - name: Build Toolkit 🏗
              run: npm run build
