name: toolkit-ci

on: pull_request

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2

            - name: Setup Node 💾
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install Dependencies 📥
              run: npm ci --workspaces="true" --include-workspace-root="true"

            - name: Run Tests 🧪
              run: npm run test

    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2

            - name: Setup Node 💾
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install Dependencies 📥
              run: npm ci --workspaces="true" --include-workspace-root="true"

            - name: Run Format Check 🌸
              run: npm run fmt

            - name: Run Lint Check 🔍
              run: npm run lint

    build-toolkit:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2

            - name: Setup Node 💾
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install Dependencies 📥
              run: npm ci --workspaces="true" --include-workspace-root="true"

            - name: Build Toolkit 🏗
              run: npm run build
