name: Test, Lint, and Build

on: pull_request

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2

            - name: Setup Node 💾
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install Dependencies 📥
              run: npm install

            - name: Run Tests 🧪
              run: npm run test

    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2

            - name: Setup Node 💾
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install Dependencies 📥
              run: npm install

            - name: Run Lint 🔍
              run: npm run lint

            - name: Run Format Check 🌸
              run: npm run fmt:check

    build-toolkit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2

            - name: Setup Node 💾
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install Dependencies 📥
              run: npm install

            - name: Build Toolkit 🏗
              run: npm run build

    build-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2

            - name: Setup Node 💾
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install Dependencies 📥
              run: npm install

            - name: Build Docs 🏗
              run: npm run build:storybook
