name: docs

on:
    push:
        branches:
            - main

jobs:
    deploy-docs:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2

            - name: Install Dependencies 📥
              run: npm install

            - name: Build Docs 🔧
              run: npm run build:docs

            - name: Deploy Docs 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.3
              with:
                  branch: gh-pages
                  folder: storybook-static
